export const INTERACTION_CLASSIFICATION = [
    'PRODUCT_INQUIRY:PRODUCT_AVAILABILITY',
    'PRODUCT_INQUIRY:SPECIFICATIONS',
    'PRODUCT_INQUIRY:PRICING',
    'PRODUCT_INQUIRY:COMPARISONS',
    'PRODUCT_INQUIRY:RECOMMENDATIONS',
  
    'ORDER_MANAGEMENT:ORDER_STATUS',
    'ORDER_MANAGEMENT:MODIFICATIONS',
    'ORDER_MANAGEMENT:CANCELLATIONS',
    'ORDER_MANAGEMENT:TRACKING',
  
    'RETURNS_AND_REFUNDS:RETURN_REQUESTS',
    'RETURNS_AND_REFUNDS:REFUND_STATUS',
    'RETURNS_AND_REFUNDS:EXCHANGE_INQUIRIES',
  
    'SHIPPING_AND_DELIVERY:SHIPPING_OPTIONS',
    'SHIPPING_AND_DELIVERY:DELIVERY_TIMES',
    'SHIPPING_AND_DELIVERY:SHIPPING_COSTS',
    'SHIPPING_AND_DELIVERY:INTERNATIONAL_SHIPPING',
  
    'PROMOTIONS_AND_DISCOUNTS:COUPON_CODES',
    'PROMOTIONS_AND_DISCOUNTS:ONGOING_PROMOTIONS',
    'PROMOTIONS_AND_DISCOUNTS:ELIGIBILITY_CRITERIA',
  
    'ACCOUNT_AND_PROFILE_MANAGEMENT:LOGIN_ISSUES',
    'ACCOUNT_AND_PROFILE_MANAGEMENT:PASSWORD_RESETS',
    'ACCOUNT_AND_PROFILE_MANAGEMENT:PROFILE_UPDATES',
  
    'TECHNICAL_SUPPORT:WEBSITE_ERRORS',
    'TECHNICAL_SUPPORT:APP_GLITCHES',
    'TECHNICAL_SUPPORT:FEATURE_MALFUNCTIONS',
  
    'FEEDBACK_AND_REVIEWS:PRODUCT_FEEDBACK',
    'FEEDBACK_AND_REVIEWS:SERVICE_REVIEWS',
    'FEEDBACK_AND_REVIEWS:TESTIMONIALS',
  
    'GENERAL_INQUIRIES:BUSINESS_HOURS',
    'GENERAL_INQUIRIES:LOCATION_DETAILS',
    'GENERAL_INQUIRIES:CONTACT_INFORMATION',
  
    'COMPLAINTS_AND_ISSUES:PRODUCT_DEFECTS',
    'COMPLAINTS_AND_ISSUES:SERVICE_DISSATISFACTION',
    'COMPLAINTS_AND_ISSUES:NEGATIVE_EXPERIENCES',
  
    'COLLABORATION_AND_PARTNERSHIP_REQUESTS:INFLUENCER_COLLABORATIONS',
    'COLLABORATION_AND_PARTNERSHIP_REQUESTS:BUSINESS_PARTNERSHIPS',
    'COLLABORATION_AND_PARTNERSHIP_REQUESTS:SPONSORSHIPS',
  
    'EVENT_AND_WEBINAR_QUERIES:EVENT_DETAILS',
    'EVENT_AND_WEBINAR_QUERIES:REGISTRATION_ISSUES',
    'EVENT_AND_WEBINAR_QUERIES:SCHEDULES',
  
    'PAYMENT_AND_BILLING:PAYMENT_FAILURES',
    'PAYMENT_AND_BILLING:BILLING_DISCREPANCIES',
    'PAYMENT_AND_BILLING:INVOICE_REQUESTS',
  
    'PRODUCT_CUSTOMIZATION_REQUESTS:CUSTOM_ORDERS',
    'PRODUCT_CUSTOMIZATION_REQUESTS:PERSONALIZATION_OPTIONS',
    'PRODUCT_CUSTOMIZATION_REQUESTS:SPECIAL_REQUESTS',
  
    'OUT_OF_SCOPE_OR_IRRELEVANT_MESSAGES:SPAM',
    'OUT_OF_SCOPE_OR_IRRELEVANT_MESSAGES:UNRELATED_CONTENT',
    'OUT_OF_SCOPE_OR_IRRELEVANT_MESSAGES:UNCLEAR_MESSAGES',
  ];
  